// Do not edit. This file is machine generated by the Resource DLL Wizard.

library Airport;

{ITE} {DFMFileType} {AboutProgram.dfm}
{ITE} {DFMFileType} {Calendar.dfm}
{ITE} {DFMFileType} {EditFlights.dfm}
{ITE} {DFMFileType} {InfoReisy.dfm}
{ITE} {DFMFileType} {Mainmenu.dfm}
{ITE} {DFMFileType} {OknoProdazhi.dfm}
{ITE} {DFMFileType} {ReturnBilet.dfm}
{ITE} {DFMFileType} {Statistika.dfm}
{ITE} {DFMFileType} {Unit3.dfm}
{ITE} {DFMFileType} {AboutProgram.dfm}
{ITE} {DFMFileType} {Calendar.dfm}
{ITE} {DFMFileType} {EditFlights.dfm}
{ITE} {DFMFileType} {InfoReisy.dfm}
{ITE} {DFMFileType} {Mainmenu.dfm}
{ITE} {DFMFileType} {OknoProdazhi.dfm}
{ITE} {DFMFileType} {ReturnBilet.dfm}
{ITE} {DFMFileType} {Statistika.dfm}
{ITE} {RCFileType} {Win32\Release\Airport_DRC.rc}

{$R 'AboutProgram.dfm' 'Form2:TForm'}
{$R 'Calendar.dfm' 'Form9:TForm'}
{$R 'EditFlights.dfm' 'Form8:TForm'}
{$R 'InfoReisy.dfm' 'Form5:TForm'}
{$R 'Mainmenu.dfm' 'Form1:TForm'}
{$R 'OknoProdazhi.dfm' 'Form4:TForm'}
{$R 'ReturnBilet.dfm' 'Form7:TForm'}
{$R 'Statistika.dfm' 'Form6:TForm'}
{$R 'Unit3.dfm' 'DataModule3:TDataModule'}
{$R 'AboutProgram.dfm' 'Form2:TForm'}
{$R 'Calendar.dfm' 'Form9:TForm'}
{$R 'EditFlights.dfm' 'Form8:TForm'}
{$R 'InfoReisy.dfm' 'Form5:TForm'}
{$R 'Mainmenu.dfm' 'Form1:TForm'}
{$R 'OknoProdazhi.dfm' 'Form4:TForm'}
{$R 'ReturnBilet.dfm' 'Form7:TForm'}
{$R 'Statistika.dfm' 'Form6:TForm'}
{$R 'Win32\Release\Airport_DRC.res' 'Win32\Release\Airport_DRC.rc'}

{$E ENU}

begin
end.
