//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace KursovayaAvtoparkAvtobusov
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class KursovayaAvtoparkAvtobusovEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new KursovayaAvtoparkAvtobusovEntities object using the connection string found in the 'KursovayaAvtoparkAvtobusovEntities' section of the application configuration file.
        /// </summary>
        public KursovayaAvtoparkAvtobusovEntities() : base("name=KursovayaAvtoparkAvtobusovEntities", "KursovayaAvtoparkAvtobusovEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new KursovayaAvtoparkAvtobusovEntities object.
        /// </summary>
        public KursovayaAvtoparkAvtobusovEntities(string connectionString) : base(connectionString, "KursovayaAvtoparkAvtobusovEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new KursovayaAvtoparkAvtobusovEntities object.
        /// </summary>
        public KursovayaAvtoparkAvtobusovEntities(EntityConnection connection) : base(connection, "KursovayaAvtoparkAvtobusovEntities")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Marshuti> Marshutis
        {
            get
            {
                if ((_Marshutis == null))
                {
                    _Marshutis = base.CreateObjectSet<Marshuti>("Marshutis");
                }
                return _Marshutis;
            }
        }
        private ObjectSet<Marshuti> _Marshutis;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Marshutis EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMarshutis(Marshuti marshuti)
        {
            base.AddObject("Marshutis", marshuti);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KursovayaAvtoparkAvtobusovModel", Name="Marshuti")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Marshuti : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Marshuti object.
        /// </summary>
        /// <param name="nomer_Marshuta">Initial value of the Nomer_Marshuta property.</param>
        public static Marshuti CreateMarshuti(global::System.Int64 nomer_Marshuta)
        {
            Marshuti marshuti = new Marshuti();
            marshuti.Nomer_Marshuta = nomer_Marshuta;
            return marshuti;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Nomer_Marshuta
        {
            get
            {
                return _Nomer_Marshuta;
            }
            set
            {
                if (_Nomer_Marshuta != value)
                {
                    OnNomer_MarshutaChanging(value);
                    ReportPropertyChanging("Nomer_Marshuta");
                    _Nomer_Marshuta = StructuralObject.SetValidValue(value, "Nomer_Marshuta");
                    ReportPropertyChanged("Nomer_Marshuta");
                    OnNomer_MarshutaChanged();
                }
            }
        }
        private global::System.Int64 _Nomer_Marshuta;
        partial void OnNomer_MarshutaChanging(global::System.Int64 value);
        partial void OnNomer_MarshutaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nachalni_Punkt
        {
            get
            {
                return _Nachalni_Punkt;
            }
            set
            {
                OnNachalni_PunktChanging(value);
                ReportPropertyChanging("Nachalni_Punkt");
                _Nachalni_Punkt = StructuralObject.SetValidValue(value, true, "Nachalni_Punkt");
                ReportPropertyChanged("Nachalni_Punkt");
                OnNachalni_PunktChanged();
            }
        }
        private global::System.String _Nachalni_Punkt;
        partial void OnNachalni_PunktChanging(global::System.String value);
        partial void OnNachalni_PunktChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Konechni_Punkt
        {
            get
            {
                return _Konechni_Punkt;
            }
            set
            {
                OnKonechni_PunktChanging(value);
                ReportPropertyChanging("Konechni_Punkt");
                _Konechni_Punkt = StructuralObject.SetValidValue(value, true, "Konechni_Punkt");
                ReportPropertyChanged("Konechni_Punkt");
                OnKonechni_PunktChanged();
            }
        }
        private global::System.String _Konechni_Punkt;
        partial void OnKonechni_PunktChanging(global::System.String value);
        partial void OnKonechni_PunktChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Voditel
        {
            get
            {
                return _Voditel;
            }
            set
            {
                OnVoditelChanging(value);
                ReportPropertyChanging("Voditel");
                _Voditel = StructuralObject.SetValidValue(value, true, "Voditel");
                ReportPropertyChanged("Voditel");
                OnVoditelChanged();
            }
        }
        private global::System.String _Voditel;
        partial void OnVoditelChanging(global::System.String value);
        partial void OnVoditelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Model_Avtobusa
        {
            get
            {
                return _Model_Avtobusa;
            }
            set
            {
                OnModel_AvtobusaChanging(value);
                ReportPropertyChanging("Model_Avtobusa");
                _Model_Avtobusa = StructuralObject.SetValidValue(value, true, "Model_Avtobusa");
                ReportPropertyChanged("Model_Avtobusa");
                OnModel_AvtobusaChanged();
            }
        }
        private global::System.String _Model_Avtobusa;
        partial void OnModel_AvtobusaChanging(global::System.String value);
        partial void OnModel_AvtobusaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Vremya_Proezda
        {
            get
            {
                return _Vremya_Proezda;
            }
            set
            {
                OnVremya_ProezdaChanging(value);
                ReportPropertyChanging("Vremya_Proezda");
                _Vremya_Proezda = StructuralObject.SetValidValue(value, true, "Vremya_Proezda");
                ReportPropertyChanged("Vremya_Proezda");
                OnVremya_ProezdaChanged();
            }
        }
        private global::System.String _Vremya_Proezda;
        partial void OnVremya_ProezdaChanging(global::System.String value);
        partial void OnVremya_ProezdaChanged();

        #endregion

    }

    #endregion

}
