//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 14-Dec-21 13:24:55
namespace KursovayaAvtoparkAvtobusov
{
    
    /// <summary>
    /// There are no comments for KursovayaAvtoparkAvtobusovModel.Marshuti in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Nomer_Marshuta
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="KursovayaAvtoparkAvtobusovModel", Name="Marshuti")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Marshuti : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Marshuti object.
        /// </summary>
        /// <param name="nomer_Marshuta">Initial value of Nomer_Marshuta.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Marshuti CreateMarshuti(long nomer_Marshuta)
        {
            Marshuti marshuti = new Marshuti();
            marshuti.Nomer_Marshuta = nomer_Marshuta;
            return marshuti;
        }
        /// <summary>
        /// There are no comments for property Nomer_Marshuta in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public long Nomer_Marshuta
        {
            get
            {
                return this._Nomer_Marshuta;
            }
            set
            {
                this.OnNomer_MarshutaChanging(value);
                this.ReportPropertyChanging("Nomer_Marshuta");
                this._Nomer_Marshuta = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Nomer_Marshuta");
                this.OnNomer_MarshutaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private long _Nomer_Marshuta;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNomer_MarshutaChanging(long value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNomer_MarshutaChanged();
        /// <summary>
        /// There are no comments for property Nachalni_Punkt in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Nachalni_Punkt
        {
            get
            {
                return this._Nachalni_Punkt;
            }
            set
            {
                this.OnNachalni_PunktChanging(value);
                this.ReportPropertyChanging("Nachalni_Punkt");
                this._Nachalni_Punkt = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Nachalni_Punkt");
                this.OnNachalni_PunktChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Nachalni_Punkt;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNachalni_PunktChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNachalni_PunktChanged();
        /// <summary>
        /// There are no comments for property Konechni_Punkt in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Konechni_Punkt
        {
            get
            {
                return this._Konechni_Punkt;
            }
            set
            {
                this.OnKonechni_PunktChanging(value);
                this.ReportPropertyChanging("Konechni_Punkt");
                this._Konechni_Punkt = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Konechni_Punkt");
                this.OnKonechni_PunktChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Konechni_Punkt;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnKonechni_PunktChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnKonechni_PunktChanged();
        /// <summary>
        /// There are no comments for property Voditel in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Voditel
        {
            get
            {
                return this._Voditel;
            }
            set
            {
                this.OnVoditelChanging(value);
                this.ReportPropertyChanging("Voditel");
                this._Voditel = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Voditel");
                this.OnVoditelChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Voditel;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnVoditelChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnVoditelChanged();
        /// <summary>
        /// There are no comments for property Model_Avtobusa in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Model_Avtobusa
        {
            get
            {
                return this._Model_Avtobusa;
            }
            set
            {
                this.OnModel_AvtobusaChanging(value);
                this.ReportPropertyChanging("Model_Avtobusa");
                this._Model_Avtobusa = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Model_Avtobusa");
                this.OnModel_AvtobusaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Model_Avtobusa;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnModel_AvtobusaChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnModel_AvtobusaChanged();
        /// <summary>
        /// There are no comments for property Vremya_Proezda in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Vremya_Proezda
        {
            get
            {
                return this._Vremya_Proezda;
            }
            set
            {
                this.OnVremya_ProezdaChanging(value);
                this.ReportPropertyChanging("Vremya_Proezda");
                this._Vremya_Proezda = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Vremya_Proezda");
                this.OnVremya_ProezdaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Vremya_Proezda;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnVremya_ProezdaChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnVremya_ProezdaChanged();
    }
    /// <summary>
    /// There are no comments for KursovayaAvtoparkAvtobusovEntities in the schema.
    /// </summary>
    public partial class KursovayaAvtoparkAvtobusovEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new KursovayaAvtoparkAvtobusovEntities object using the connection string found in the 'KursovayaAvtoparkAvtobusovEntities' section of the application configuration file.
        /// </summary>
        public KursovayaAvtoparkAvtobusovEntities() : 
                base("name=KursovayaAvtoparkAvtobusovEntities", "KursovayaAvtoparkAvtobusovEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new KursovayaAvtoparkAvtobusovEntities object.
        /// </summary>
        public KursovayaAvtoparkAvtobusovEntities(string connectionString) : 
                base(connectionString, "KursovayaAvtoparkAvtobusovEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new KursovayaAvtoparkAvtobusovEntities object.
        /// </summary>
        public KursovayaAvtoparkAvtobusovEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "KursovayaAvtoparkAvtobusovEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Marshutis in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Marshuti> Marshutis
        {
            get
            {
                if ((this._Marshutis == null))
                {
                    this._Marshutis = base.CreateQuery<Marshuti>("[Marshutis]");
                }
                return this._Marshutis;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Marshuti> _Marshutis;
        /// <summary>
        /// There are no comments for Marshutis in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToMarshutis(Marshuti marshuti)
        {
            base.AddObject("Marshutis", marshuti);
        }
    }
}
